name: runner test

on:
    
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Java 11
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          java -version  # Verify the Java version

      - name: Install Maven
        run: |
          sudo apt-get install -y maven
          mvn -version  # Verify Maven version

      - name: Install Node.js and npm
        run: |
          sudo apt-get install -y nodejs npm
          node -v   # Verify Node.js version
          npm -v    # Verify npm version

      - name: Install & run Appium 2.0
        run: |
          sudo npm install -g appium@next
          appium --version  # Verify Appium version
          appium --log-level info &
          appium &>/dev/null &
          appium driver install uiautomator2
          appium driver list --installed  # Verify installed drivers

      - name: Download APK from GitHub Release
        run: |
          # Replace this URL with your actual GitHub release URL
          RELEASE_URL="https://github.com/manthan39/AppiumFramework/releases/tag/test/app-cd-vendor-debug.apk"
          curl -L -o app-cd-vendor-debug.apk $RELEASE_URL  # Download APK

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: |
            # Wait for the emulator to boot up
            adb wait-for-device
            adb shell input keyevent 82
            echo "$(pwd)/app-cd-vendor-debug.apk"
            adb install -r /home/runner/work/mobileFramework/mobileFramework/app-cd-vendor-debug.apk
            mvn clean test -Dplatform=android
